# prod config
spring:
  application:
    name: icc-stts
  data:
    mongodb:
      uri: mongodb://admin:J3sus%402025@192.168.1.231:27017,192.168.1.232:27017,192.168.1.233:27017/ICCDB?authSource=admin&maxPoolSize=100&replicaSet=rs0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.231:3306/iccdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: J3sus@2025
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  kafka:
    bootstrap-servers: 192.168.1.231:9092,192.168.1.232:9092,192.168.1.233:9092

  redis:
    timeout: 6000ms
    database: 0
    cluster:
      nodes:
        - 192.168.1.231:6379
        - 192.168.1.232:6379
        - 192.168.1.233:6379
        - 192.168.1.231:6380
        - 192.168.1.232:6380
        - 192.168.1.233:6380
      max-redirects: 3
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 80
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 2


logging:
  config: classpath:logback-prod.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除后
      logic-delete-value: 1

file:
  download:
    dir: D:/ICC-APP/ICC-STTS/files

ms:
  speech:
    key: c3ff3a6c796543c89637358dbdee3aa5
    region: southeastasia

ffmpeg:
  path:
    main: ffmpeg
    probe: ffprobe

tts:
  config:
    ssml: '<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="{lang}"><voice name="{voiceName}"><prosody rate="5%" volume="120%">{content}</prosody></voice></speak>'

audio:
  socket:
    url: ws://192.168.1.179:8186/icc-audio/ws/audio/icc-stts
  save:
    path: D:/ICC-APP/ICC-STTS/files
  trans:
    path: D:/ICC-APP/ICC-STTS/trans
